version: '3.7'
services:
  medishare-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/var/www/medishare.david-losert.com
  medishare-mysql:
    image: mysql
    volumes:
      - mysql-medishare-data:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: medishare
      MYSQL_USER: medishare
      MYSQL_PASSWORD: MediShare
  medishare-backend:
    build:
      context: ./api.flask.v1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
volumes:
  mysql-medishare-data:
    name: medishare-data