version: '3.7'
services:
  medishare-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/var/www/medishare.david-losert.com
  medishare-backend:
    build:
      context: ./api.flask.v1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"