version: '3.6'
services:
  mysql-medishare:
    image: mysql
    #restart: always
    volumes:
      - mysql-medishare-data:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: medishare
      MYSQL_USER: medishare
      MYSQL_PASSWORD: MediShare

  adminer-medishare:
    image: adminer
    #restart: always
    ports:
      - 8090:8080

volumes:
  mysql-medishare-data:
    name: medishare-data
    