openapi: "3.0.0"
info:
  version: 1.0.0
  title: WirVsVirus Hackathon Medishare API
  license:
    name: MIT
servers:
  - url: http://medishare.wirvsvirus.com/v1
paths:
  /categories:
    get:
      description: A list of all categories
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Categories"
    post:
      description: Create new category
      responses:
        '201':
          description: Created
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        '400':
          description: Not Found
          content: 
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string        
  /categories/{id}:
    get:
      description: Get single category
      parameters:
        - name:  id
          in: path
          schema:
           type: integer
           format: int32
          required: true
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        '404':
          description: Not Found
          content: 
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /advertisements:
    get:
      summary: Get all current searches order by how close they are
      operationId: listAdvertisements
      tags:
        - Advertisement
      responses:
        '200':
          description: A paged list of itemRequest
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Advertisements"
    post:
      summary: Create a new Advertisement
      operationId: createAdvertisement
      tags:
        - Advertisement
      responses:
        '201':
          description: Null response
components:
  schemas:
    Category:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        unit:
          type: string
    Categories:
      type: array
      items:
        $ref: "#/components/schemas/Category"
    MedicalPractice:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        lanr:
          type: string
        phone:
          type: string
        zip:
          type: string
        place_name:
          type: string
    Advertisement:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: "#/components/schemas/Category"
        amount:
          type: number
        desiredDate:
          type: string
        medicalPractice:
          $ref: "#/components/schemas/MedicalPractice"
    Advertisements:
      type: array
      items:
        $ref: "#/components/schemas/Advertisement"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
