openapi: "3.0.0"
info:
  version: 1.0.0
  title: WirVsVirus Hackathon Medishare API
  license:
    name: MIT
servers:
  - url: http://medishare.wirvsvirus.com/v1
paths:
  /categories:
    get:
      description: A list of all categories
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Categories"
  /item-requests:
    get:
      summary: Get all current searches order by how close they are
      operationId: listItemRequests
      tags:
        - ItemRequest
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged list of itemRequest
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ItemRequests"
    post:
      summary: Create a new Item-Request
      operationId: createItemRequest
      tags:
        - ItemRequest
      responses:
        '201':
          description: Null response
components:
  schemas:
    Category:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Categories:
      type: array
      items:
        $ref: "#/components/schemas/Category"
    Requestor:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        phone:
          type: string
        location:
          type: string
    ItemRequest:
      type: object
      required:
        - id
        - requestorId
        - name
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: "#/components/schemas/Category"
        amount:
          type: number
        requestor:
          $ref: "#/components/schemas/Requestor"
    ItemRequests:
      type: array
      items:
        $ref: "#/components/schemas/ItemRequest"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
